# Generated by Django 3.1.6 on 2021-02-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210204_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='shop/default/default.jpg', upload_to='shop/img', verbose_name='대표 이미지'),
        ),
    ]
